version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
      include: "scope"
    
  # Enable version updates for Python dependencies in pixi.toml
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      python-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"
